export { default as areDeepEqual } from 'fast-deep-equal'
export { default as memoizeOne } from 'memoize-one'

export * from 'ramda'

export * from './areShallowEqual'
export * from './arrayKeyedMap'
export * from './deferred'
export * from './delay'
export * from './delayOne'
export * from './emptyArray'
export * from './emptyObject'
export * from './ensureTruthyArray'
export * from './fastCartesian'
export * from './fromEntries'
export * from './getForm'
export { identity } from './identity'
export * from './isPlainObject'
export * from './isPromiseLike'
export * from './joinClassNames'
export * from './joinEventHandlers'
export * from './joinRefs'
export * from './keyPartitioner'
export * from './maybe'
export * from './memo'
export * from './noop'
export * from './pendingPromiseLike'
export * from './preventDefaultEventHandler'
export * from './root'
export * from './suspendIndefinitely'
export * from './useConfigurator'
export * from './useEffectOnce'
export * from './useFirstInstanceOfLatestValue'
export * from './useMemoizeOneValue'
export * from './useSilencedLayoutEffect'
