export * from './areArraysShallowEqual'
export * from './deferred'
export * from './delay'
export * from './fromEntries'
export * from './identity'
export * from './isPlainObject'
export * from './noop'
